apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  template:
    spec:
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: backend
          image: ${DOCKER_HUB_USERNAME}/backend:latest
          imagePullPolicy: Always
