apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  template:
    spec:
      imagePullSecrets:
        - name: docker-hub-secret
      containers:
        - name: frontend
          image: ${DOCKER_HUB_USERNAME}/frontend:latest
          imagePullPolicy: Always